### ISSUE TITLE
Why upload a zipped version of the starter pack?

### ISSUE THREAD

**Issue by ooade** [jalasem/materializecss_starter#1]

**Comment by jalasem** [comment]
Well, I did that just to make it easy for some folks out there that don't have good proficiency using the command line

**Comment by jalasem** [comment]
Any better suggestion?

**Comment by ooade** [comment]
Yeah. Delete the zipped version and add instructions on how to actually download the Project; a picture will be fine

**Comment by ooade** [comment]
You can do something like: 
### Steps to download:
![dl](https://cloud.githubusercontent.com/assets/11811904/23846552/3dc3b60c-07ce-11e7-9c4e-27f2f7bef2ee.png)

**Comment by jalasem** [comment]
yeah great suggestion. Thanks!
